
export const env_variables = {
    MYSQL_HOST_LOCAL: process.env.MYSQL_HOST_LOCAL,
    MYSQL_USERNAME_LOCAL: process.env.MYSQL_USERNAME_LOCAL,
    MYSQL_PASSSWORD_LOCAL: process.env.MYSQL_PASSSWORD_LOCAL,
    MYSQL_DATABASE_LOCAL: process.env.MYSQL_PASSSWORD_LOCAL,

    MYSQL_HOST_DEV: process.env.MYSQL_HOST_DEV,
    MYSQL_USERNAME_DEV: process.env.MYSQL_USERNAME_DEV,
    MYSQL_PASSSWORD_DEV: process.env.MYSQL_PASSSWORD_DEV,
    MYSQL_DATABASE_DEV: process.env.MYSQL_DATABASE_DEV,
    
    MYSQL_HOST_PROD: process.env.MYSQL_HOST_PROD,
    MYSQL_USERNAME_PROD: process.env.MYSQL_USERNAME_PROD,
    MYSQL_PASSSWORD_PROD: process.env.MYSQL_PASSSWORD_PROD,
    MYSQL_DATABASE_PROD: process.env.MYSQL_DATABASE_PROD,
} 